version: '3'
services:
  image_pantry:
    image: image_pantry:latest
    build: 
      context: ./ImagePantry
      dockerfile: Dockerfile
    container_name: image_pantry
    volumes:
      - type: bind
        source: "/Users/kennethbass/Documents/kitchensync/"
        target: "/app"
    ports:
    - '5000:5000'
    environment: 
    # - FLASK_APP=app.py
    - FLASK_DEBUG=True # FLASK_ENVIRONMENT depcrecated
    - PORT=5000
    #depends_on:
    #restart: on-failure